<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.DomainPrimitives\BuildingBlocks.DomainPrimitives.csproj" />
    <ProjectReference Include="..\Account.Application\Account.Application.csproj" />
    <ProjectReference Include="..\Account.Domain\Account.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="Confluent.Kafka" />
  </ItemGroup>

</Project>
