services:
  postgres:
    image: postgres:17-alpine@sha256:18cfe3ef5e6815560c98237d6216d1e5119702fb0f3894c8785dd58b8bbe5d73
    environment:
      POSTGRES_DB: twilight_toolchain
      POSTGRES_USER: twilight
      POSTGRES_PASSWORD: development-only
    ports:
      - "54329:5432"
