/* This file is generated by frontend/scripts/generate-p0-types.mjs from docs/contracts/p0/openapi.json. */
/* Do not hand-edit; update the locked P0 contract and regenerate. */

export interface RegisterRequest {
  readonly handle: string;
  readonly password: string;
}

export interface LoginRequest {
  readonly handle: string;
  readonly password: string;
}

export interface TextPostCreateRequest {
  readonly content: string;
  readonly visibility: 'public' | 'followers' | 'private';
}

export interface SettingsPatch {
  readonly profileVisibility?: 'public' | 'followers' | 'private';
  readonly allowMessages?: boolean;
}

export interface User {
  readonly id: string;
  readonly handle: string;
  readonly policyVersion: number;
}

export interface Settings {
  readonly profileVisibility: string;
  readonly allowMessages: boolean;
  readonly policyVersion: number;
}

export interface Session {
  readonly accessToken: string;
  readonly expiresAt: string;
}

export interface Resource {
  readonly id: string;
  readonly version: number;
}

export interface Collection {
  readonly items: ReadonlyArray<{}>;
  readonly nextCursor: unknown;
}

export interface Error {
  readonly error: {
    readonly code: string;
    readonly message: string;
    readonly correlationId: string;
  };
}
